spring.application.name=etecfer
# Configuração do Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/etecfer_db
spring.datasource.username=postgres
spring.datasource.password=postdba

#Atualizar As Tabelas do Banco De Dados Automaticamente
spring.jpa.hibernate.ddl-auto=update

#Não Formatar os comandos SQL no console
spring.jpa.properties.hibernate.format_sql=false

#Mostrar os Comandos SQL no console 
spring.jpa.show-sql=true

#configurar a porta do servidor 
server.port=8080